const BASE = (import.meta.env.VITE_API_URL ?? '') + '/api';

async function req(method, path, body) {
  const res = await fetch(BASE + path, {
    method,
    headers: body ? { 'Content-Type': 'application/json' } : {},
    body: body ? JSON.stringify(body) : undefined,
    credentials: 'include',
  });
  return res.json();
}

export const api = {
  auth: {
    characters: () => req('GET', '/auth/characters'),
    stats: () => req('GET', '/auth/stats'),
    login: (login, haslo, rememberMe) => req('POST', '/auth/login', { login, haslo, rememberMe }),
    register: (login, haslo, powtorzHaslo) => req('POST', '/auth/register', { login, haslo, powtorzHaslo }),
    classes: () => req('GET', '/auth/classes'),
    logout: () => req('POST', '/auth/logout'),
    myCharacters: () => req('GET', '/auth/my-characters'),
    servers: () => req('GET', '/auth/servers'),
  },
  adminDash: {
    sessionCheck:  ()           => req('POST',  '/admin/session-check'),
    status:        ()           => req('GET',   '/admin/server-status'),
    config:        ()           => req('GET',   '/admin/server-config'),
    saveConfig:    (changes)    => req('POST',  '/admin/server-config', { changes }),
    broadcast:     (message)    => req('POST',  '/admin/broadcast',     { message }),
    auditLog:      (params={})  => req('GET',   `/admin/audit-log${Object.keys(params).length ? '?'+new URLSearchParams(params) : ''}`),
    players:       (search)     => req('GET',   `/admin/players${search?`?search=${encodeURIComponent(search)}`:''}` ),
    banPlayer:     (id, reason) => req('POST',  `/admin/ban/${id}`,     { reason }),
    unbanPlayer:   (id)         => req('POST',  `/admin/unban/${id}`),
    kickPlayer:    (id)         => req('POST',  `/admin/kick/${id}`),
    setRank:       (id, ranga)  => req('POST',  '/admin/set-rank',      { id, ranga }),
    teleport:      (id,mapa,x,y)=> req('POST',  '/admin/teleport',      { id, mapa, x, y }),
    teleportSelf:  (mapa,x,y)   => req('POST',  '/admin/teleport-self',  { mapa, x, y }),
    gotoPlayer:    (targetId)   => req('POST',  '/admin/goto-player',    { targetId }),
    pullPlayer:    (targetId)   => req('POST',  '/admin/pull-player',    { targetId }),
    giveGold:      (id, amount) => req('POST',  '/admin/give-gold',     { id, amount }),
    giveExp:       (id, amount) => req('POST',  '/admin/give-exp',      { id, amount }),
    setLevel:      (id, level)  => req('POST',  '/admin/set-level',     { id, level }),
    setPrestige:   (id, p)      => req('POST',  '/admin/set-prestige',  { id, prestige: p }),
    setClass:      (id, k)      => req('POST',  '/admin/set-class',     { id, profesja: k }),
    healPlayer:    (id)         => req('POST',  '/admin/heal-player',   { id }),
    stats:         ()           => req('GET',   '/admin/stats'),
    chat:          ()           => req('GET',   '/admin/chat'),
    clearChat:     ()           => req('POST',  '/admin/clear-chat'),
    mobs:          (mapaId)     => req('GET',   `/admin/mobs/${mapaId}`),
    resetMobs:     (mapaId)     => req('POST',  '/admin/reset-mobs',    { mapaId }),
    resetAllMobs:  ()           => req('POST',  '/admin/reset-all-mobs'),
    maps:          ()           => req('GET',   '/admin/maps'),
    items:         (search)     => req('GET',   `/admin/items${search?`?search=${encodeURIComponent(search)}`:''}` ),
    giveItem:      (postacId, itemId) => req('POST', '/admin/give-item', { postacId, itemId }),
    healAll:       ()           => req('POST',  '/admin/heal-all'),
    bossStatus:    ()           => req('GET',   '/admin/boss-status'),
    spawnBoss:     (bossId)     => req('POST',  '/admin/spawn-boss',      { bossId }),
    killBoss:      ()           => req('POST',  '/admin/kill-boss'),
    eventsList:    ()           => req('GET',   '/admin/events-list'),
    activateEvent: (eventId)    => req('POST',  '/admin/activate-event',  { eventId }),
    deactivateEvent:()          => req('POST',  '/admin/deactivate-event'),
    servers:       ()           => req('GET',   '/admin/servers'),
    createServer:  (data)       => req('POST',  '/admin/servers',       data),
    updateServer:  (id, data)   => req('PATCH', `/admin/servers/${id}`, data),
    deleteServer:  (id)         => req('DELETE',`/admin/servers/${id}`),
  },
  game: {
    state:      ()    => req('GET',  '/game/state'),
    move:       (dir) => req('POST', '/game/move', { direction: dir }),
    worldState: ()    => req('GET',  '/game/world-state'),
    tiles:      (mapaId) => req('GET', `/game/tiles/${mapaId}`),
  },
  events: {
    active:   ()    => req('GET',  '/events/active'),
    shop:     ()    => req('GET',  '/events/shop'),
    buy:      (d)   => req('POST', '/events/shop/buy', d),
    activate: (d)   => req('POST', '/events/admin/activate', d),
  },
  chat: {
    get: () => req('GET', '/chat'),
    send: (tresc, kanal) => req('POST', '/chat', { tresc, kanal }),
  },
  combat: {
    mobInfo:  (mobId)                    => req('GET',  `/combat/mob-info/${mobId}`),
    action:   (mobId, action, itemId)    => req('POST', '/combat/action', { mobId, action, itemId }),
    skill:    (mobId, skillId)           => req('POST', '/combat/skill',  { mobId, skillId }),
    pvp:      (targetId)                 => req('POST', '/combat/pvp',    { targetId }),
    // ── Nowy system v2 ──────────────────────────────────────────────────────
    start2:   (mobId)                    => req('POST', '/combat/start2',   { mobId }),
    turn2:    (mobId, action, skillId, itemId) => req('POST', '/combat/turn2', { mobId, action, skillId, itemId }),
    state2:   ()                         => req('GET',  '/combat/state2'),
    abort2:   ()                         => req('DELETE','/combat/abort2'),
  },
  world: {
    maps:           ()              => req('GET',    '/world/maps'),
    updateMap:      (id, data)      => req('PUT',    `/world/maps/${id}`, data),
    tiles:          (mapaId)        => req('GET',    `/world/tiles/${mapaId}`),
    saveTiles:      (mapaId, data)  => req('PUT',    `/world/tiles/${mapaId}`, data),
    mobs:           (mapaId)        => req('GET',    `/world/mobs/${mapaId}`),
    createMob:      (data)          => req('POST',   '/world/mobs', data),
    updateMob:      (id, data)      => req('PUT',    `/world/mobs/${id}`, data),
    deleteMob:      (id)            => req('DELETE', `/world/mobs/${id}`),
    respawnMob:     (id)            => req('POST',   `/world/mobs/${id}/respawn`),
    npcs:           (mapaId)        => req('GET',    `/world/npcs/${mapaId}`),
    createNpc:      (data)          => req('POST',   '/world/npcs', data),
    updateNpc:      (id, data)      => req('PUT',    `/world/npcs/${id}`, data),
    deleteNpc:      (id)            => req('DELETE', `/world/npcs/${id}`),
    portals:        (mapaId)        => req('GET',    `/world/portals/${mapaId}`),
    createPortal:   (data)          => req('POST',   '/world/portals', data),
    deletePortal:   (id)            => req('DELETE', `/world/portals/${id}`),
    blockers:       (mapaId)        => req('GET',    `/world/blockers/${mapaId}`),
    addBlocker:     (data)          => req('POST',   '/world/blockers', data),
    removeBlocker:  (data)          => req('DELETE', '/world/blockers', data),
    itemsLoot:      (search)        => req('GET',    `/world/items-loot${search?`?search=${encodeURIComponent(search)}`:''}`),
    createItemLoot: (data)          => req('POST',   '/world/items-loot', data),
    updateItemLoot: (id, data)      => req('PUT',    `/world/items-loot/${id}`, data),
    deleteItemLoot: (id)            => req('DELETE', `/world/items-loot/${id}`),
    shopItems:      (shopId)        => req('GET',    `/world/shop-items/${shopId}`),
    createShopItem: (data)          => req('POST',   '/world/shop-items', data),
    updateShopItem: (id, data)      => req('PUT',    `/world/shop-items/${id}`, data),
    deleteShopItem: (id)            => req('DELETE', `/world/shop-items/${id}`),
    lootPacks:      ()              => req('GET',    '/world/loot-packs'),
    addLootPackItem:(packId, data)  => req('POST',   `/world/loot-packs/${packId}/items`, data),
    removeLootEntry:(id)            => req('DELETE', `/world/loot-packs/entries/${id}`),
  },
  items: {
    inventory:      ()              => req('GET',  '/items/inventory'),
    equip:          (itemId,action) => req('POST', '/items/equip', { itemId, action }),
    sell:           (itemId)        => req('POST', '/items/sell', { itemId }),
    use:            (itemId)        => req('POST', '/items/use', { itemId }),
    shop:           (shopId)        => req('GET',  `/items/shop/${shopId}`),
    buy:            (itemId,shopId) => req('POST', '/items/buy', { itemId, shopId }),
    templeHeal:     ()              => req('POST', '/items/temple-heal'),
    templeStatus:   ()              => req('GET',  '/items/temple-status'),
    bossPortal:     ()              => req('GET',  '/items/boss-portal'),
    useBossPortal:  ()              => req('POST', '/items/use-boss-portal'),
    guildBoard:     ()              => req('GET',  '/items/guild-board'),
    eventZone:      ()              => req('GET',  '/items/event-zone'),
  },
  character: {
    heal:         ()         => req('POST', '/character/heal'),
    pvpToggle:    ()         => req('POST', '/character/pvp-toggle'),
    skills:       ()         => req('GET',  '/character/skills'),
    friends:      ()         => req('GET',  '/character/friends'),
    pvpHistory:   ()         => req('GET',  '/character/pvp-history'),
    outfits:      ()         => req('GET',  '/character/outfits'),
    setOutfit:    (outfitId) => req('POST', '/character/outfit', { outfitId }),
    titles:       ()         => req('GET',  '/character/titles'),
    equipTitle:   (id)       => req('POST', `/character/titles/${id}/equip`),
    unequipTitle: ()         => req('POST', '/character/titles/unequip'),
    prestigeInfo: ()         => req('GET',  '/character/prestige-info'),
    prestige:     ()         => req('POST', '/character/prestige'),
    assignStat:   (stat)     => req('POST', '/character/assign-stat', { stat }),
  },
  social: {
    profile:      (id)       => req('GET',  `/social/profile/${id}`),
    guildMy:      ()         => req('GET',  '/social/guild/my'),
    guildList:    ()         => req('GET',  '/social/guild/list'),
    guildCreate:  (d)        => req('POST', '/social/guild/create',  d),
    guildJoin:    (guildId)  => req('POST', '/social/guild/join',    { guildId }),
    guildLeave:   ()         => req('POST', '/social/guild/leave'),
    guildPromote: (targetId, ranga) => req('POST', '/social/guild/promote', { targetId, ranga }),
    guildKick:    (targetId) => req('POST', '/social/guild/kick',    { targetId }),
    // Guild ranks
    guildRanks:       (guildId) => req('GET',    `/social/guild/ranks/${guildId}`),
    guildRankCreate:  (data)    => req('POST',   '/social/guild/ranks', data),
    guildRankUpdate:  (id,data) => req('PUT',    `/social/guild/ranks/${id}`, data),
    guildRankDelete:  (id)      => req('DELETE', `/social/guild/ranks/${id}`),
    guildMemberRank:  (memberId, ranga) => req('PUT', `/social/guild/member-rank/${memberId}`, { niestandardowa_ranga: ranga }),
    // Treasury
    guildDeposit:     (amount)        => req('POST', '/social/guild/treasury/deposit',  { amount }),
    guildWithdraw:    (amount, opis)  => req('POST', '/social/guild/treasury/withdraw', { amount, opis }),
    guildTreasuryLog: ()              => req('GET',  '/social/guild/treasury/log'),
    // Bulletin
    guildBulletin:    (text) => req('PUT', '/social/guild/bulletin', { ogloszenie: text }),
    // Recruitment
    guildOpenClose:       (otwarta) => req('PUT',  '/social/guild/open-close', { otwarta }),
    guildApply:           (gildia_id, tresc) => req('POST', '/social/guild/apply', { gildia_id, tresc }),
    guildApplications:    ()   => req('GET',  '/social/guild/applications'),
    guildApplicationsMy:  ()   => req('GET',  '/social/guild/applications/my'),
    guildAppAccept:       (id) => req('POST', `/social/guild/applications/${id}/accept`),
    guildAppReject:       (id) => req('POST', `/social/guild/applications/${id}/reject`),
    // Ranking
    guildRanking: () => req('GET', '/social/guild/ranking'),
    // Contributions
    guildContributions: () => req('GET', '/social/guild/contributions'),
    // Wars
    guildWarDeclare: (targetId) => req('POST', '/social/guild/war/declare', { target_guild_id: targetId }),
    guildWarActive:  ()         => req('GET',  '/social/guild/war/active'),
    guildWarEnd:     (warId)    => req('POST', `/social/guild/war/end/${warId}`),
    guildWarHistory: ()         => req('GET',  '/social/guild/war/history'),
    // Quests
    guildQuestCreate:  (data) => req('POST', '/social/guild/quest/create', data),
    guildQuestActive:  ()     => req('GET',  '/social/guild/quest/active'),
    guildQuestCollect: ()     => req('POST', '/social/guild/quest/collect'),
    // Territory
    guildTerritoryClaim:  (mapa_id) => req('POST', '/social/guild/territory/claim',   { mapa_id }),
    guildTerritoryAbandon: ()       => req('POST', '/social/guild/territory/abandon'),
    guildTerritoryAll:     ()       => req('GET',  '/social/guild/territory/all'),
    // Buffs
    guildBuffs:       ()     => req('GET',  '/social/guild/buffs'),
    guildBuffUpgrade: (type) => req('POST', '/social/guild/buffs/upgrade', { type }),
    // Relations
    guildRelationSet:    (target_guild_id, typ) => req('POST',   '/social/guild/relation',               { target_guild_id, typ }),
    guildRelationDelete: (targetId)             => req('DELETE', `/social/guild/relation/${targetId}`),
    guildRelations:      ()                     => req('GET',    '/social/guild/relations'),
    guildTerritoryIncome: ()                    => req('GET',    '/social/guild/territory/income'),
    // Raids
    guildRaidStart:    (data)   => req('POST', '/social/guild/raid/start',           data),
    guildRaidJoin:     (raidId) => req('POST', `/social/guild/raid/join/${raidId}`),
    guildRaidComplete: (raidId) => req('POST', `/social/guild/raid/complete/${raidId}`),
    guildRaidActive:   ()       => req('GET',  '/social/guild/raid/active'),
    addComment:    (profileId, tresc) => req('POST',   `/social/profile/comment/${profileId}`, { tresc }),
    deleteComment: (cid)              => req('DELETE', `/social/profile/comment/${cid}`),
    messages:     ()         => req('GET',  '/social/messages'),
    unreadCount:  ()         => req('GET',  '/social/messages/unread-count'),
    sendMessage:  (toId, tresc) => req('POST', '/social/messages/send', { toId, tresc }),
    readMessage:  (messageId)   => req('POST', '/social/messages/read', { messageId }),
    readAll:      ()         => req('POST', '/social/messages/read-all'),
    friends:      ()         => req('GET',  '/social/friends'),
    addFriend:    (targetId) => req('POST', '/social/friends/add',    { targetId }),
    removeFriend: (targetId) => req('POST', '/social/friends/remove', { targetId }),
  },
  trade: {
    session: () => req('GET', '/trade/session'),
    cancel:  () => req('POST', '/trade/cancel'),
  },
  craft: {
    materials: ()    => req('GET',  '/craft/materials'),
    recipes:   ()    => req('GET',  '/craft/recipes'),
    create:    (id)  => req('POST', `/craft/create/${id}`),
    upgrade:   (id)  => req('POST', `/craft/upgrade/${id}`),
  },
  fishing: {
    cast:       (d) => req('POST', '/fishing/cast', d),
    catch:      (d) => req('POST', '/fishing/catch', d),
    reel:       (d) => req('POST', '/fishing/reel', d),
    relax:      (d) => req('POST', '/fishing/relax', d),
    cancel:     (d) => req('POST', '/fishing/cancel', d),
    sellAll:    ()  => req('POST', '/fishing/sell-all'),
    stats:      ()  => req('GET',  '/fishing/stats'),
    ranking:    ()  => req('GET',  '/fishing/ranking'),
    equipment:  ()  => req('GET',  '/fishing/equipment'),
    upgradeRod: (d) => req('POST', '/fishing/upgrade-rod', d),
  },
  talents: {
    tree:    ()    => req('GET',  '/talents/tree'),
    invest:  (id)  => req('POST', '/talents/invest', { talent_id: id }),
    reset:   ()    => req('POST', '/talents/reset'),
    points:  ()    => req('GET',  '/talents/available-points'),
  },
  auction: {
    list:   (params) => req('GET', `/auction?${new URLSearchParams(params||{})}`),
    my:     ()       => req('GET', '/auction/my'),
    post:   (d)      => req('POST', '/auction/list', d),
    buy:    (id)     => req('POST', `/auction/buy/${id}`),
    cancel: (id)     => req('POST', `/auction/cancel/${id}`),
  },
  worldboss: {
    active:            ()         => req('GET',  '/worldboss/active'),
    attack:            ()         => req('POST', '/worldboss/attack'),
    bossAttack:        ()         => req('POST', '/worldboss/boss-attack'),
    bossSkill:         (skillId)  => req('POST', '/worldboss/boss-skill', { skillId }),
    bossFlee:          ()         => req('POST', '/worldboss/boss-flee'),
    bossItem:          (itemId)   => req('POST', '/worldboss/boss-item', { itemId }),
    mySession:         ()         => req('GET',  '/worldboss/my-session'),
    leaderboard:       (id)       => req('GET',  `/worldboss/leaderboard/${id}`),
    ranking:           (id)       => req('GET',  `/worldboss/ranking/${id}`),
    achievements:      ()         => req('GET',  '/worldboss/achievements'),
    guildContribution: (id)       => req('GET',  `/worldboss/guild-contribution/${id}`),
    history:           ()         => req('GET',  '/worldboss/history'),
  },
  dungeons: {
    list:     ()    => req('GET',  '/dungeons/list'),
    active:   ()    => req('GET',  '/dungeons/active'),
    create:   (d)   => req('POST', '/dungeons/create', d),
    join:     (id)  => req('POST', `/dungeons/join/${id}`),
    complete: (id)  => req('POST', `/dungeons/complete/${id}`),
    leave:    ()    => req('POST', '/dungeons/leave'),
  },
  dungeons2: {
    list:        ()                       => req('GET',    '/dungeons2/list'),
    active:      ()                       => req('GET',    '/dungeons2/active'),
    enter:       (dungeon_id, trudnosc)   => req('POST',   '/dungeons2/enter',       { dungeon_id, trudnosc }),
    nextFloor:   ()                       => req('POST',   '/dungeons2/next-floor'),
    claimChest:  ()                       => req('POST',   '/dungeons2/claim-chest'),
    complete:    ()                       => req('POST',   '/dungeons2/complete'),
    leave:       ()                       => req('POST',   '/dungeons2/leave'),
    history:     ()                       => req('GET',    '/dungeons2/history'),
    reportDeath: ()                       => req('POST',   '/dungeons2/report-death'),
  },
  offline: {
    start:   (d) => req('POST', '/offline/start', d),
    collect: ()  => req('POST', '/offline/collect'),
    status:  ()  => req('GET',  '/offline/status'),
  },
  quests: {
    list:       ()            => req('GET',  '/quests'),
    forNpc:     (npcId)       => req('GET',  `/quests/npc/${npcId}`),
    accept:     (questId)     => req('POST', '/quests/accept',  { questId }),
    turnin:     (questId)     => req('POST', '/quests/turnin',  { questId }),
    adminList:  ()            => req('GET',  '/quests/admin'),
    adminCreate:(data)        => req('POST', '/quests/admin',   data),
    adminUpdate:(id, data)    => req('PUT',  `/quests/admin/${id}`, data),
    adminDelete:(id)          => req('DELETE',`/quests/admin/${id}`),
    chains:        ()           => req('GET',  '/quests/chains'),
    chainQuests:   (id)         => req('GET',  `/quests/chains/${id}/quests`),
    daily:         ()           => req('GET',  '/quests/daily'),
    weekly:        ()           => req('GET',  '/quests/weekly'),
    reputation:    ()           => req('GET',  '/quests/reputation'),
    chooseReward:  (qId, idx)   => req('POST', `/quests/turnin/${qId}/choose`, { choice_index: idx }),
    ranking:       (qId)        => req('GET',  `/quests/ranking/${qId}`),
    history:       ()           => req('GET',  '/quests/history'),
    achievements:  ()           => req('GET',  '/quests/achievements'),
    checkAch:      ()           => req('POST', '/quests/achievements/check'),
    activeEvents:  ()           => req('GET',  '/quests/events/active'),
    toggleEvent:   (d)          => req('POST', '/quests/events/toggle', d),
  },
};
