// Wybor sprite'ow z arkusza: nr = indeks w manifescie, kx/ky = zajmowane kafle,
// rozciagnij = dopasuj dokladnie do siatki (tereny, mury, ploty)
const WYBOR = [
  // ── tereny 32x32 ──
  { id: 't_trawa1', nr: 1, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_trawa2', nr: 7, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_trawa3', nr: 15, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_trawa4', nr: 20, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_trawa_kw1', nr: 4, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_trawa_kw2', nr: 12, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_trawa_kw3', nr: 23, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_trawa_kw4', nr: 24, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_ziemia1', nr: 17, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_droga1', nr: 8, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_bruk1', nr: 6, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_bruk2', nr: 10, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_bruk3', nr: 11, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_bruk4', nr: 14, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_bruk5', nr: 18, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_bruk6', nr: 22, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_woda1', nr: 28, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_woda2', nr: 29, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 't_woda3', nr: 30, kx: 1, sh: 1, rozciagnij: 1 },

  // ── drzewa i zielen ──
  { id: 'o_swierk', nr: 167 }, { id: 'o_swierk_maly', nr: 161 },
  { id: 'o_dab', nr: 156 }, { id: 'o_dab_wysoki', nr: 165 },
  { id: 'o_drzewo_jesien', nr: 170 }, { id: 'o_drzewo_owoc', nr: 162 },
  { id: 'o_drzewo3', nr: 158 }, { id: 'o_drzewo4', nr: 173 },
  { id: 'o_drzewo5', nr: 168 }, { id: 'o_drzewo6', nr: 169 },
  { id: 'o_krzak1', nr: 177 }, { id: 'o_krzak2', nr: 178 },
  { id: 'o_krzak3', nr: 163 }, { id: 'o_krzak4', nr: 166 },
  { id: 'o_krzak_kwiat', nr: 182 }, { id: 'o_krzak_jagody', nr: 181 },
  { id: 'o_trawa_wys1', nr: 184 }, { id: 'o_trawa_wys2', nr: 186 },
  { id: 'o_trawa_wys3', nr: 187 }, { id: 'o_trawa_wys4', nr: 196 },
  { id: 'o_trawa_wys5', nr: 198 },
  { id: 'o_kwiaty1', nr: 200 }, { id: 'o_kwiaty2', nr: 205 },
  { id: 'o_kwiaty3', nr: 192 }, { id: 'o_kwiaty4', nr: 189 },
  { id: 'o_kwiaty5', nr: 203 },
  { id: 'o_grzyby', nr: 183 }, { id: 'o_paproc', nr: 202 },
  { id: 'o_liscie', nr: 201 }, { id: 'o_pniak', nr: 175 },
  { id: 'o_glaz', nr: 194 }, { id: 'o_glaz2', nr: 199 },
  { id: 'o_sadzonka', nr: 171 }, { id: 'o_krzew_suchy', nr: 188 },
  { id: 'o_bluszcz', nr: 193 },

  // ── budynki ──
  { id: 'o_dom_maly', nr: 56, kx: 2, ky: 2 },
  { id: 'o_dom_sredni', nr: 59, kx: 2, ky: 2 },
  { id: 'o_dom_duzy', nr: 52, kx: 2, ky: 3 },
  { id: 'o_dom_pietrowy', nr: 53, kx: 2, ky: 4 },
  { id: 'o_dom_kamienny', nr: 64, kx: 2, ky: 2 },
  { id: 'o_dom_wielki', nr: 54, kx: 3, ky: 6 },
  { id: 'o_wiatrak', nr: 60, kx: 2, ky: 3 },
  { id: 'o_wieza', nr: 63, kx: 1, ky: 2 },
  { id: 'o_fontanna', nr: 145, kx: 2, ky: 2 },
  { id: 'o_studnia_k', nr: 82, kx: 1, ky: 1 },

  // ── mury miejskie (dopasowane do siatki) ──
  { id: 'o_mur_k', nr: 219, kx: 1, sh: 1.2, rozciagnij: 1 },
  { id: 'o_mur_bluszcz', nr: 237, kx: 2, sh: 1.5, rozciagnij: 1 },
  { id: 'o_mur_brama', nr: 226, kx: 2, sh: 1.7, rozciagnij: 1 },
  { id: 'o_mur_luk', nr: 239, kx: 2, sh: 1.1, rozciagnij: 1 },
  { id: 'o_wieza_mur', nr: 230, kx: 1, sh: 1.9, rozciagnij: 1 },
  { id: 'o_brama_duza', nr: 234, kx: 3, sh: 2.5, rozciagnij: 1 },
  { id: 'o_mur_rog', nr: 231, kx: 1, sh: 1.35, rozciagnij: 1 },

  // ── ploty i dekoracje ──
  { id: 'o_plot_poz', nr: 89, kx: 1, sh: 0.8, rozciagnij: 1 },
  { id: 'o_plot_pion', nr: 99 },
  { id: 'o_plot_brama', nr: 101, kx: 1, sh: 1, rozciagnij: 1 },
  { id: 'o_latarnia_k', nr: 67 }, { id: 'o_latarnia2', nr: 104 },
  { id: 'o_pochodnia', nr: 96 },
  { id: 'o_beczka_k', nr: 112 }, { id: 'o_beczka2', nr: 128 },
  { id: 'o_beczka_woda', nr: 119 }, { id: 'o_dzban', nr: 126 },
  { id: 'o_skrzynka', nr: 121 }, { id: 'o_stol', nr: 107 },
  { id: 'o_lawka', nr: 132 }, { id: 'o_lawka2', nr: 127 },
  { id: 'o_stragan1', nr: 115 }, { id: 'o_stragan2', nr: 117, kx: 2 },
  { id: 'o_stragan3', nr: 122 }, { id: 'o_stragan4', nr: 130 },
  { id: 'o_stragan5', nr: 139 },
  { id: 'o_tablica_k', nr: 114 }, { id: 'o_drogowskaz', nr: 129 },
  { id: 'o_posag1', nr: 133 }, { id: 'o_posag2', nr: 134 }, { id: 'o_posag3', nr: 135 },
  { id: 'o_sztandar_n', nr: 98 }, { id: 'o_sztandar_c', nr: 97 },
  { id: 'o_ognisko_k', nr: 146 }, { id: 'o_koryto', nr: 110 },
  { id: 'o_kwietnik1', nr: 152 }, { id: 'o_kwietnik2', nr: 153 },
  { id: 'o_kwietnik3', nr: 154 }, { id: 'o_kwietnik4', nr: 150 },
];
